### ISSUE TITLE
Starter Kit: UX/UI Improvements for Open Sentencing

### ISSUE THREAD

**Issue by upkarlidder** [embrace-call-for-code/outcarcerate-ui#67]
### Background on the problem the feature will solve/improved user experience
Open Sentencing's UI has a lot of potential to be a powerful tool for public defenders. However, some features have not been fully implemented, and others require improvements to improve the usability and user experience. 

### Describe the solution you'd like

Upgrade the existing UI pages with more advanced and interactive components that improves the look, feel and user experience for the end user. Ensure UI is pulling in real data with help from backend team.

### Tasks 
- [ ] Investigate the latest version of Angular.js that works with the Carbon Design System.
- [ ] Conduct design thinking/planning sessions as needed
- [ ] Identify gaps between existing Open Sentencing UI and the [mock up Invision App](https://ibm.invisionapp.com/share/Q5O0KIVUNE8#/screens)
- [ ] Identify any gaps in user journey (work with Open Sentencing Team)
- [ ] propose updates to features/user journey using wireframes
- [ ] fix any documentation errors
- [ ] After discussion implement enhanced user interface in Angular.js
- [ ] existing UI filter needs to be connected to the API
- [ ] ensure site is responsive
- [ ] determine dependencies on back end needed to test out UX - refer here: https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/44

### Related Issues
- [ ] #15 
- [ ] #16 
- [ ] #17 
- [ ] #24 
- [ ] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/44
- [ ] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/56

### Acceptance Criteria 

- The website should reflect a more modernized  & responsive application that allows for visitors to accomplish the intended functionalities of the application more intuitively and with delight. The app should also reflect Level 1 accessibility guidelines based on the IBM [Equal Access Toolkit
](https://www.ibm.com/able/toolkit/plan/#pace-of-completion)

Read more about Accessibility Testing https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/53

**Comment by demilolu** [comment]
not stale in action

**Comment by demilolu** [comment]
@wisdomkeeper and Demi to discuss and flesh out the tasks required for this issue
