### ISSUE TITLE
Epic - Public Defender enters a new case

### ISSUE THREAD

**Issue by chenhuyr** [embrace-call-for-code/outcarcerate-ui#86]
### Background on the problem the feature will solve/improved user experience
In this main use case scenario, data has not yet been entered for the case. The person entering may be a public defender or a staff member.

## User Story 1
A public defender ‘Bob’ has a new case to work on.  He has been assigned a young man who is accused of committing second degree arson in Michigan and is facing the full penalty of 20 years.
Per quick research he learns:

The penalty for second degree arson is a felony conviction punishable by up to 20 years in prison, or a fine not more than $20,000 or 3 times the value of the property damaged or destroyed, whichever is greater, or both
Bob wants to know if his client’s possible sentence of 20 years is fair given his race is black.  He has seen his white clients receive lesser sentences.

He will go into our tool and input all of the case information.  He is curious if bias detection will flag that black defendants receive higher sentences typically for this crime.  If this occurs, he will share this information with his client and present it to the prosecution. 
Bob will share the information by printing a final result form from his computer.  The print-out should clearly show BIAS was detected per the algorithm and that his defendant is facing more time in jail simply due to the color of his skin.  He will give the prosecutor, judge and defendant copies of the document.  With data to help, he talks the sentencing team into less time in jail.

## User Story 2
A public defender Lea has asked her staff member Jill to enter 15 new cases into the Open Sentencing tool.  Jill gets busy entering case details one at a time and saving.  In the end, she prints the details of each case for Lea and places them in a binder.  All the bias found in each case is highlighted.  Jill makes sure Lea is updated on which cases has disparate sentences based on race so action can be taken. (Note: this makes me think a summary report would be good in some way).

## Adding Defendant Demographic Details
- #88  
As a Public Defender/Staff Member, 
I want to add the defendants **name** to a new case, 
so that the new case will have demographic details to determine if bias was present in sentencing

- [ ] As a Public Defender/Staff Member, 
I want to add an **existing** the defendants **name** to a new case, 
so that the new case will have demographic details to determine if bias was present in sentencing

- #87 Edel Altares
As a Public Defender/Staff Member, 
I want to add an add the defendants **race** to a new case, 
so that the new case will have demographic details to determine if bias was present in sentencing

- #89 Ryan Cheng
As a Public Defender/Staff Member, 
I want to add an add the defendants **gender** to a new case, 
so that the new case will have demographic details to determine if bias was present in sentencing

- [ ] As a Public Defender/Staff Member with diverse disabilities, 
I want to an accessible form to add demographic and case details, 
so that the new case will have demographic details to determine if bias was present in sentencing

## Adding Defendant Case Details
- #93 Lewis Nikuze
- #94 Walter Alvarez and Kurtis Niedling
As a Public Defender/Staff Member, 
I want to an select applicable charges to the case, 
so that the new case will have case details to determine if bias was present in sentencing

- [ ] As a Public Defender/Staff Member, 
I want to an select remove unnecessary charges to the case, 
so that the new case will have case details to determine if bias was present in sentencing

- [ ] As a Public Defender/Staff Member, 
I want to an select remove unnecessary charges to the case, 
so that the new case will have case details to determine if bias was present in sentencing

- [ ] As a Public Defender/Staff Member, 
I want to classify the new case as drug related, 
so that the new case will have case details to determine if bias was present in sentencing

- #96 
As a Public Defender/Staff Member, 
I want to add the criminal history category when adding a new drug related case. 
Currently, the criminal history category dropdown shows a list of genders when clicked.

- #97 
As a Public Defender/Staff Member, 
I want to add the criminal history category when adding a new drug related case. 
Currently, the criminal history category dropdown shows a list of genders when clicked.

- #98
As a Public Defender/Staff Member, 
I want to add estimated sentence length measured in months when adding a new drug related case. 
Currently, the estimated sentence dropdown shows a list of races when clicked.

### Acceptance Criteria 
N/A
