### ISSUE TITLE
Add New Case | Demographic Details | Add Defendants Gender

### ISSUE THREAD

**Issue by chenhuyr** [embrace-call-for-code/outcarcerate-ui#89]
### Background on the problem the feature will solve/improved user experience
As a Public Defender/Staff Member,
I want to add an add the defendants **gender** to a new case,
so that the new case will have demographic details to determine if bias was present in sentencing

### Describe the solution you'd like
- Match gender list with the list on the aggregator
- Extract gender to its own class
- Extract validation to its own module
- Add unit tests
- Show "Select Gender" placeholder
- Show error when Gender is not select after first touch.

### Tasks 
- [x] Add unknown to the existing list. 
- [x] Match gender list with the list on the aggregator
- [x] Extract gender to its own class
- [x] Extract validation to its own module
- [x] Add unit tests
- [x] Show "Select Gender" placeholder
- [x] Show error when Gender is not select after first touch.

### Acceptance Criteria 

- [x] Creates a new case with the defendants gender
- [x] Gender options should be Female, Male, Other, Unknown
