### ISSUE TITLE
Show List of Charges when clicking into Charges selector

### ISSUE THREAD

**Issue by w-alvarez** [embrace-call-for-code/outcarcerate-ui#94]
### Background on the problem the feature will solve/improved user experience
When the user focuses the Charges selector, there are no options presented by default. The user must begin typing for a limited quantity of options to be suggested.

### Describe the solution you'd like
When the Charges selector is focused, there should be a few options that the user can selected from by default without needing to type anything into the filter.

### Tasks 
- [x] Add a label to the dropdown that says "Charges" to denote what the list is of
- [x] Clicking on Charges selector, a list of default options is presented to the user.
- [x] Clicking the dropdown should show/hide the default options.

### Acceptance Criteria 
When the user selects either the Charges selector or the charges dropdown, they will see a list of default charges without needing to type anything. This list will be prefaced with a label that says "Charges."
